<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	
	<PropertyGroup>
		<Description>The official Voucherly .NET library, supporting .NET 6.0+.</Description>
		<Version>1.5.0</Version>
		<Authors>Voucherly, Francesco Bognini</Authors>
		<Company>Voucherly</Company>
		<PackageTags>voucherly;payment;credit;cards;money;gateway;buoni pasto</PackageTags>
		<PackageIcon>icon.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseFile>LICENSE</PackageLicenseFile>
		<PackageProjectUrl>https://github.com/voucherly/voucherly-dotnet-sdk</PackageProjectUrl>
		<RepositoryUrl>https://github.com/voucherly/voucherly-dotnet-sdk</RepositoryUrl>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FastIDs.TypeId" Version="1.2.1" />
		<PackageReference Include="FastIDs.TypeId.Serialization.SystemTextJson" Version="1.1.1" />
		<PackageReference Include="fbognini.Sdk" Version="3.2.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.0" />

		<PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
		<PackageReference Include="Microsoft.Extensions.Options" Version="8.0.1" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\..\LICENSE" Pack="true" PackagePath="" />
		<None Include="..\..\README.md" Pack="true" PackagePath="" />
		<None Include="icon.png" Pack="true" Visible="false" PackagePath="" />
	</ItemGroup>

</Project>
